feat: 📝 add pictures and REX links
RdvSpeakers/camping-des-speakers-website pull request #47
Opened 2022-06-15 08:29 UTC by philippart-s

Hello la team !

Une proposition de page pour lister tous les retours sur cette belle conf ❤️

2022-06-15 12:04 UTC, philippart-s commented
j'ai mis aussi des vidéos, bref tout type de supports tant que c'est un REX 😉 

@LostInBrittany @Steffy29 @scraly

2022-06-17 13:28 UTC, scraly requested changes

2022-06-17 13:28 UTC, scraly commented on _includes/layouts/home.11ty.js
> +    <a href="${data.site[data.locale].rex.url}" class="button">Les REX</a>
```suggestion
    <a href="${data.site[data.locale].rex.url}" class="button">Les ReX en articles et vidéos</a>    
```

2022-06-17 13:28 UTC, scraly commented on _includes/layouts/home.11ty.js
> +    <h2>Ce qu'en disent les participant.e.s</h2>
```suggestion
    <h2>Ce qu'en disent les participant.e.s :</h2>
```

2022-06-17 13:28 UTC, scraly commented on content/pages/rex.md
> +Quels meilleurs retours que les images, voici les [photos](https://t.co/x0dYbyvmpp) de l'édition 2022.
```suggestion
Quels meilleurs retours que des articles (et vidéos) de speakers, sponsors et participants qui ont assisté à la première édition du Camping des Speakers : 
```

2022-06-17 13:28 UTC, scraly commented on content/pages/rex.md
> + - [CALM#88](https://www.youtube.com/watch?v=xia4J1nXKSE)
```suggestion
 - 🎥 [CALM#88](https://www.youtube.com/watch?v=xia4J1nXKSE)
```

2022-06-17 13:28 UTC, scraly commented
Merciiii
pour les photos, je penses qu'on va les mettre autre part, plus visible, avec les eux liens : album collaboratif et des benevoles, ça peut etre sympa (et on attend les photos "officielles" encore ^^)

2022-06-18 12:50 UTC, philippart-s commented
@scraly je ne peux pas approver tes commits, je pense que ça vient du fait que je ne dois pas avoir les droits de commit & push sur votre repo.
Il faudra donc que tu le fasses 😉

2022-06-20 10:24 UTC, scraly approved these changes

2022-12-17 13:40 UTC, scraly commented
Je push (enfin) cette super PR sur l'edition 2022 du site : 2022.camping-speakers.fr !

2022-12-17 13:41 UTC, closed without merging